# Generated by Django 4.2.16 on 2024-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('cleaned_name', models.CharField(max_length=50)),
                ('value', models.SmallIntegerField()),
            ],
        ),
    ]
